// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {monitor} from '../models';
import {main} from '../models';
import {host} from '../models';
import {record} from '../models';

export function Connect(arg1:string,arg2:number):Promise<monitor.Capabilities>;

export function DeleteHost(arg1:string):Promise<void>;

export function DeleteScheduled(arg1:string,arg2:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function DownloadScheduledAndPlay(arg1:string,arg2:string):Promise<main.LogMeta>;

export function EstimateScheduled(arg1:string):Promise<monitor.RecEstimate>;

export function IsRecording():Promise<boolean>;

export function ListHosts():Promise<Array<host.Host>>;

export function ListScheduled(arg1:string):Promise<Array<monitor.RecMeta>>;

export function LogFrames(arg1:string):Promise<Array<monitor.Frame>>;

export function NethogsInstall(arg1:string):Promise<void>;

export function NethogsRollback(arg1:string):Promise<void>;

export function OpenLogDialog():Promise<main.LogMeta>;

export function ProcessHistory(arg1:string,arg2:number):Promise<Array<record.Point>>;

export function SaveHost(arg1:host.Host):Promise<host.Host>;

export function SetInterval(arg1:string,arg2:number):Promise<void>;

export function StartRecording(arg1:string):Promise<string>;

export function StartScheduled(arg1:string,arg2:number,arg3:number,arg4:string):Promise<monitor.RecMeta>;

export function StopRecording():Promise<string>;

export function StopScheduled(arg1:string,arg2:string):Promise<void>;
