// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteHost(arg1) {
  return window['go']['main']['App']['DeleteHost'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function IsLogNamed() {
  return window['go']['main']['App']['IsLogNamed']();
}

export function ListHosts() {
  return window['go']['main']['App']['ListHosts']();
}

export function LogFrames(arg1) {
  return window['go']['main']['App']['LogFrames'](arg1);
}

export function NethogsInstall(arg1) {
  return window['go']['main']['App']['NethogsInstall'](arg1);
}

export function NethogsRollback(arg1) {
  return window['go']['main']['App']['NethogsRollback'](arg1);
}

export function OpenLogDialog() {
  return window['go']['main']['App']['OpenLogDialog']();
}

export function ProcessHistory(arg1, arg2) {
  return window['go']['main']['App']['ProcessHistory'](arg1, arg2);
}

export function SaveHost(arg1) {
  return window['go']['main']['App']['SaveHost'](arg1);
}

export function SaveLogDialog() {
  return window['go']['main']['App']['SaveLogDialog']();
}
