// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {monitor} from '../models';
import {main} from '../models';
import {host} from '../models';
import {record} from '../models';
import {pwledger} from '../models';

export function ApplyUpdate(arg1:updater.UpdateInfo):Promise<void>;

export function AutoUpdate():Promise<updater.AutoUpdateResult>;

export function BundleLogCollect(arg1:string):Promise<string>;

export function CancelCaptureDownload(arg1:string,arg2:string):Promise<void>;

export function CancelLogCollect():Promise<void>;

export function CaptureEnv(arg1:string):Promise<monitor.CapEnv>;

export function CaptureSHA256(arg1:string,arg2:string):Promise<string>;

export function ChangePasswords(arg1:string,arg2:string):Promise<void>;

export function CheckForUpdate():Promise<updater.UpdateInfo>;

export function ChooseCaptureSavePath(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function ChooseLogCollectFolder():Promise<string>;

export function CollectLogs(arg1:Array<main.LogCollectTask>,arg2:string):Promise<main.LogCollectResult>;

export function Connect(arg1:string,arg2:number):Promise<monitor.Capabilities>;

export function ConnectMany(arg1:Array<string>,arg2:number):Promise<Array<main.ClusterConnectResult>>;

export function DeleteCapture(arg1:string,arg2:string):Promise<void>;

export function DeleteHost(arg1:string):Promise<void>;

export function DeleteLogCollectLeftover(arg1:string,arg2:string):Promise<void>;

export function DeleteScheduled(arg1:string,arg2:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function DisconnectMany(arg1:Array<string>):Promise<void>;

export function DownloadCapture(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DownloadScheduledAndPlay(arg1:string,arg2:string):Promise<main.LogMeta>;

export function DownloadScheduledDayAndPlay(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number):Promise<main.LogMeta>;

export function DownloadScheduledSlicesAndPlay(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number):Promise<main.LogMeta>;

export function EstimateScheduled(arg1:string):Promise<monitor.RecEstimate>;

export function ForgetCapture(arg1:string,arg2:string):Promise<void>;

export function GetCurrentVersion():Promise<string>;

export function GetPendingReleaseNotes():Promise<updater.PendingNotes>;

export function IsRecording():Promise<boolean>;

export function KillProcess(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function ListCaptures(arg1:string):Promise<Array<monitor.CapMeta>>;

export function ListHosts():Promise<Array<host.Host>>;

export function ListScheduled(arg1:string):Promise<Array<monitor.RecMeta>>;

export function LocalCapturePath(arg1:string,arg2:string):Promise<string>;

export function LocalOperator():Promise<string>;

export function LogCollectCatalog():Promise<monitor.LogCatalog>;

export function LogCollectLeftovers(arg1:Array<string>):Promise<Array<monitor.LogLeftover>>;

export function LogCollectPlan(arg1:string,arg2:monitor.LogRequest):Promise<monitor.LogPlan>;

export function LogCollectSurvey(arg1:Array<string>,arg2:number):Promise<Array<monitor.LogSurvey>>;

export function LogFrameAt(arg1:string,arg2:number):Promise<monitor.Frame>;

export function LogFrameCount(arg1:string):Promise<number>;

export function LogFrames(arg1:string):Promise<Array<monitor.Frame>>;

export function LogProcSeries(arg1:string,arg2:number):Promise<Array<record.Point>>;

export function MarkReleaseNotesSeen():Promise<void>;

export function NethogsInstall(arg1:string):Promise<void>;

export function NethogsRollback(arg1:string):Promise<void>;

export function OpenCaptureFolder(arg1:string,arg2:string):Promise<void>;

export function OpenInWireshark(arg1:string,arg2:string):Promise<void>;

export function OpenLogCollectFolder(arg1:string):Promise<void>;

export function OpenLogDialog():Promise<main.LogMeta>;

export function PasswordStatus(arg1:string):Promise<monitor.PwStatus>;

export function PrepareScheduledSlices(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<number>>;

export function ProcessHistory(arg1:string,arg2:number):Promise<Array<record.Point>>;

export function PwConfig():Promise<pwledger.Config>;

export function PwLedger(arg1:string):Promise<Array<pwledger.Entry>>;

export function RenewPasswords(arg1:string):Promise<void>;

export function ResetLogCollectCatalog():Promise<monitor.LogCatalog>;

export function SaveHost(arg1:host.Host):Promise<host.Host>;

export function SaveHosts(arg1:Array<host.Host>):Promise<Array<host.Host>>;

export function SaveLogCollectCatalog(arg1:monitor.LogCatalog):Promise<void>;

export function ServiceAction(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetInterval(arg1:string,arg2:number):Promise<void>;

export function SetPwConfig(arg1:pwledger.Config):Promise<void>;

export function ShowUpdateModeNoticeOnce():Promise<void>;

export function StartCapture(arg1:string,arg2:monitor.CapRequest):Promise<monitor.CapMeta>;

export function StartRecording(arg1:string):Promise<string>;

export function StartScheduled(arg1:string,arg2:number,arg3:number,arg4:string):Promise<monitor.RecMeta>;

export function StopCapture(arg1:string,arg2:string):Promise<monitor.CapMeta>;

export function StopCaptureForce(arg1:string,arg2:string):Promise<monitor.CapMeta>;

export function StopRecording():Promise<string>;

export function StopScheduled(arg1:string,arg2:string):Promise<void>;
