// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {monitor} from '../models';
import {host} from '../models';
import {record} from '../models';

export function Connect(arg1:string):Promise<monitor.Capabilities>;

export function DeleteHost(arg1:string):Promise<void>;

export function DiscardAndQuit():Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function IsLogNamed():Promise<boolean>;

export function KeepLogAndQuit(arg1:string):Promise<void>;

export function ListHosts():Promise<Array<host.Host>>;

export function ProcessHistory(arg1:string,arg2:number):Promise<Array<record.Point>>;

export function SaveHost(arg1:host.Host):Promise<host.Host>;

export function SaveLog(arg1:string):Promise<string>;
