// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteHost(arg1) {
  return window['go']['main']['App']['DeleteHost'](arg1);
}

export function DiscardAndQuit() {
  return window['go']['main']['App']['DiscardAndQuit']();
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function IsLogNamed() {
  return window['go']['main']['App']['IsLogNamed']();
}

export function KeepLogAndQuit(arg1) {
  return window['go']['main']['App']['KeepLogAndQuit'](arg1);
}

export function ListHosts() {
  return window['go']['main']['App']['ListHosts']();
}

export function ProcessHistory(arg1, arg2) {
  return window['go']['main']['App']['ProcessHistory'](arg1, arg2);
}

export function SaveHost(arg1) {
  return window['go']['main']['App']['SaveHost'](arg1);
}

export function SaveLog(arg1) {
  return window['go']['main']['App']['SaveLog'](arg1);
}
