// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate(arg1) {
  return window['go']['main']['App']['ApplyUpdate'](arg1);
}

export function AutoUpdate() {
  return window['go']['main']['App']['AutoUpdate']();
}

export function CancelCaptureDownload(arg1, arg2) {
  return window['go']['main']['App']['CancelCaptureDownload'](arg1, arg2);
}

export function CaptureEnv(arg1) {
  return window['go']['main']['App']['CaptureEnv'](arg1);
}

export function CaptureSHA256(arg1, arg2) {
  return window['go']['main']['App']['CaptureSHA256'](arg1, arg2);
}

export function ChangePasswords(arg1, arg2) {
  return window['go']['main']['App']['ChangePasswords'](arg1, arg2);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ChooseCaptureSavePath(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ChooseCaptureSavePath'](arg1, arg2, arg3, arg4);
}

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function ConnectMany(arg1, arg2) {
  return window['go']['main']['App']['ConnectMany'](arg1, arg2);
}

export function DeleteCapture(arg1, arg2) {
  return window['go']['main']['App']['DeleteCapture'](arg1, arg2);
}

export function DeleteHost(arg1) {
  return window['go']['main']['App']['DeleteHost'](arg1);
}

export function DeleteScheduled(arg1, arg2) {
  return window['go']['main']['App']['DeleteScheduled'](arg1, arg2);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function DisconnectMany(arg1) {
  return window['go']['main']['App']['DisconnectMany'](arg1);
}

export function DownloadCapture(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadCapture'](arg1, arg2, arg3);
}

export function DownloadScheduledAndPlay(arg1, arg2) {
  return window['go']['main']['App']['DownloadScheduledAndPlay'](arg1, arg2);
}

export function DownloadScheduledDayAndPlay(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DownloadScheduledDayAndPlay'](arg1, arg2, arg3, arg4, arg5);
}

export function DownloadScheduledSlicesAndPlay(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DownloadScheduledSlicesAndPlay'](arg1, arg2, arg3, arg4, arg5);
}

export function EstimateScheduled(arg1) {
  return window['go']['main']['App']['EstimateScheduled'](arg1);
}

export function ForgetCapture(arg1, arg2) {
  return window['go']['main']['App']['ForgetCapture'](arg1, arg2);
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetPendingReleaseNotes() {
  return window['go']['main']['App']['GetPendingReleaseNotes']();
}

export function IsRecording() {
  return window['go']['main']['App']['IsRecording']();
}

export function KillProcess(arg1, arg2, arg3) {
  return window['go']['main']['App']['KillProcess'](arg1, arg2, arg3);
}

export function ListCaptures(arg1) {
  return window['go']['main']['App']['ListCaptures'](arg1);
}

export function ListHosts() {
  return window['go']['main']['App']['ListHosts']();
}

export function ListScheduled(arg1) {
  return window['go']['main']['App']['ListScheduled'](arg1);
}

export function LocalCapturePath(arg1, arg2) {
  return window['go']['main']['App']['LocalCapturePath'](arg1, arg2);
}

export function LocalOperator() {
  return window['go']['main']['App']['LocalOperator']();
}

export function LogFrameAt(arg1, arg2) {
  return window['go']['main']['App']['LogFrameAt'](arg1, arg2);
}

export function LogFrameCount(arg1) {
  return window['go']['main']['App']['LogFrameCount'](arg1);
}

export function LogFrames(arg1) {
  return window['go']['main']['App']['LogFrames'](arg1);
}

export function LogProcSeries(arg1, arg2) {
  return window['go']['main']['App']['LogProcSeries'](arg1, arg2);
}

export function MarkReleaseNotesSeen() {
  return window['go']['main']['App']['MarkReleaseNotesSeen']();
}

export function NethogsInstall(arg1) {
  return window['go']['main']['App']['NethogsInstall'](arg1);
}

export function NethogsRollback(arg1) {
  return window['go']['main']['App']['NethogsRollback'](arg1);
}

export function OpenCaptureFolder(arg1, arg2) {
  return window['go']['main']['App']['OpenCaptureFolder'](arg1, arg2);
}

export function OpenInWireshark(arg1, arg2) {
  return window['go']['main']['App']['OpenInWireshark'](arg1, arg2);
}

export function OpenLogDialog() {
  return window['go']['main']['App']['OpenLogDialog']();
}

export function PasswordStatus(arg1) {
  return window['go']['main']['App']['PasswordStatus'](arg1);
}

export function PrepareScheduledSlices(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PrepareScheduledSlices'](arg1, arg2, arg3, arg4);
}

export function ProcessHistory(arg1, arg2) {
  return window['go']['main']['App']['ProcessHistory'](arg1, arg2);
}

export function PwConfig() {
  return window['go']['main']['App']['PwConfig']();
}

export function PwLedger(arg1) {
  return window['go']['main']['App']['PwLedger'](arg1);
}

export function RenewPasswords(arg1) {
  return window['go']['main']['App']['RenewPasswords'](arg1);
}

export function SaveHost(arg1) {
  return window['go']['main']['App']['SaveHost'](arg1);
}

export function SaveHosts(arg1) {
  return window['go']['main']['App']['SaveHosts'](arg1);
}

export function ServiceAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['ServiceAction'](arg1, arg2, arg3);
}

export function SetInterval(arg1, arg2) {
  return window['go']['main']['App']['SetInterval'](arg1, arg2);
}

export function SetPwConfig(arg1) {
  return window['go']['main']['App']['SetPwConfig'](arg1);
}

export function ShowUpdateModeNoticeOnce() {
  return window['go']['main']['App']['ShowUpdateModeNoticeOnce']();
}

export function StartCapture(arg1, arg2) {
  return window['go']['main']['App']['StartCapture'](arg1, arg2);
}

export function StartRecording(arg1) {
  return window['go']['main']['App']['StartRecording'](arg1);
}

export function StartScheduled(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartScheduled'](arg1, arg2, arg3, arg4);
}

export function StopCapture(arg1, arg2) {
  return window['go']['main']['App']['StopCapture'](arg1, arg2);
}

export function StopCaptureForce(arg1, arg2) {
  return window['go']['main']['App']['StopCaptureForce'](arg1, arg2);
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}

export function StopScheduled(arg1, arg2) {
  return window['go']['main']['App']['StopScheduled'](arg1, arg2);
}
